const CONFIG = {
    introTitle: 'Em iu à!',
    introDesc: `Anh vẫn còn nhớ như in ngày đó, cái ngày anh bị cướp đi một thứ rất quan trọng trong cuộc đời. Chính em đã lấy đi trái tim nguội lạnh của anh và cám ơn em đã sưởi ấm để nó lại tiếp tục loạn nhịp,
    btnIntro: 'hihi',
    title: '6 tháng không phải là thời gian quá dài, nhưng cũng đủ để anh nhận rõ tình cảm của bản thân. Anh yêu em',
    desc: 'Em có iu anh hong? ',
    btnYes: 'Vẫn cứ là iu anh <33',
    btnNo: 'Không, Anh à :)',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Hẹn em iu khi nào ra Hà Nội nhó <3',
    btnAccept: 'Okiiiii lun <3',
    
